### ISSUE TITLE
Unsupported metadata version 1.1, only support 1.0

### ISSUE THREAD

**Issue by shamilbi** [ido50/morgan#8]
Slackware Linux x86_64, python 3.10.10,  pip-23.0.1, setuptools-67.4.0

morgan.ini:
wheel =

output:
wheel
Traceback (most recent call last):
  File "apps/morgan/.venv/bin/morgan", line 8, in <module>
    sys.exit(main())
  File "apps/morgan_/.venv/lib64/python3.10/site-packages/morgan/__init__.py", line 458, in main
    mirror(args.index_path)
  File "apps/morgan_/.venv/lib64/python3.10/site-packages/morgan/__init__.py", line 421, in mirror
    m.mirror("{}{}".format(package, m.config["requirements"][package]))
  File "apps/morgan_/.venv/lib64/python3.10/site-packages/morgan/__init__.py", line 74, in mirror
    deps = self._mirror(requirement)
  File "apps/morgan_/.venv/lib64/python3.10/site-packages/morgan/__init__.py", line 136, in _mirror
    raise Exception(
Exception: Unsupported metadata version 1.1, only support 1.0

**Comment by shamilbi** [comment]
test:

import urllib.request
import json

PYPI_ADDRESS = "https://pypi.org/simple/"

def main():
    request = urllib.request.Request(
        "{}{}/".format(PYPI_ADDRESS, 'wheel'),
        headers={
            'Accept': 'application/vnd.pypi.simple.v1+json',
        },
    )

    data = None
    with urllib.request.urlopen(request) as response:
        data = json.load(response)
    if data:
        print(data['meta'])
        # {'_last-serial': 15716458, 'api-version': '1.1'}


if __name__ == '__main__':
    main()

**Comment by ido50** [comment]
Thanks for your contribution, published as version 0.13.1.
